# Generated by Django 3.0.7 on 2020-07-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0002_auto_20200709_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='date_of_breakup',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mucisian',
            name='date_of_death',
            field=models.DateField(null=True),
        ),
    ]
