# Generated by Django 3.0.7 on 2020-07-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0004_auto_20200709_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(related_name='bands', to='music_portal.Musician'),
        ),
        migrations.AlterField(
            model_name='band',
            name='photo',
            field=models.ImageField(blank=True, upload_to='band_photos'),
        ),
        migrations.AlterField(
            model_name='band',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='bands', to='music_portal.Song'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='photo',
            field=models.ImageField(blank=True, upload_to='musician_photos'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='songs',
            field=models.ManyToManyField(related_name='musicians', to='music_portal.Song'),
        ),
    ]
