# Generated by Django 3.0.7 on 2020-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_portal', '0006_auto_20200710_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='musician',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
